server:
  port: 8080

spring:
  application:
    name: classPilot
  datasource:
    url: jdbc:h2:mem:classPilotDb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  sql:
    init:
      platform: h2
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
  # Hibernate 설정 - 테이블 자동 생성
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  # H2 콘솔 활성화 (웹 브라우저로 DB 접속 가능)
  h2:
    console:
      enabled: true
      path: /h2-console
  # http://localhost:8080/actuator 초기 id 및 비밀번호
  security:
    user:
      name: admin
      password: password


springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

